<?php


if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

return array (
    array(
        'key' => 'emails',
        'label' => __( 'Emails', 'acf-frontend-form-element' ),
        'type' => 'list_items',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'collapsed' => 'email_id',
        'collapsable' => true,
        'min' => '',
        'max' => '',
        'layout' => 'block',
        'button_label' => __( 'Add Email', 'acf-frontend-form-element' ),
        'remove_label' => __( 'Remove Email', 'acf-frontend-form-element' ),
        'sub_fields' => array (
            array (
                'key' => 'email_id',
                'label' => __( 'Email Name', 'acf-frontend-form-element' ),
                'name' => 'name',
                'type' => 'text',
                'instructions' => __( 'Give this email an identifier', 'acf-frontend-form-element' ),
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '70',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => __( 'Email Name', 'acf-frontend-form-element' ),
                'placeholder' => __( 'Email Name', 'acf-frontend-form-element' ),
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_to_message',
                'label' => __( 'Email Addresses', 'acf-frontend-form-element' ),
                'name' => 'recipient_custom',
                'type' => 'message',
                'message' =>  __( 'Separate emails with commas. <br> To display the names and addresses, use the following format: Name&lt;address&gt;.', 'acf-frontend-form-element' ),
            ),
           
            array (
                'key' => 'email_to',
                'label' => __( 'To', 'acf-frontend-form-element' ),
                'name' => 'recipient_custom',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_to_cc',
                'label' => __( 'CC', 'acf-frontend-form-element' ),
                'name' => 'recipient_custom',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_to_bcc',
                'label' => __( 'BCC', 'acf-frontend-form-element' ),
                'name' => 'recipient_custom',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_from',
                'label' => __( 'From Email', 'acf-frontend-form-element' ),
                'name' => 'from',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_from_name',
                'label' => __( 'From Name', 'acf-frontend-form-element' ),
                'name' => 'from_name',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_reply_to',
                'label' => __( 'Reply To Email', 'acf-frontend-form-element' ),
                'name' => 'reply_to',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_reply_to_name',
                'label' => __( 'Reply To Name', 'acf-frontend-form-element' ),
                'name' => 'reply_to_name',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'wrapper' => array (
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_subject',
                'label' => __( 'Subject', 'acf-frontend-form-element' ),
                'name' => 'subject',
                'type' => 'text',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'email_content',
                'label' => __( 'Content', 'acf-frontend-form-element' ),
                'type' => 'wysiwyg',
                'dynamic_value_choices' => 1,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array(
                'key' => 'email_content_type',
                'label' => __( 'Send As', 'acf-frontend-form-element' ),
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'html',
                'choices' => array(
					'html' => __( 'HTML', 'acf-frontend-form-element' ),
					'plain' => __( 'Plain', 'acf-frontend-form-element' ),
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'form_metadata',
                'label' => __( 'Meta Data', 'acf-frontend-form-element' ),
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '75',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => [
					'date',
					'time',
					'page_url',
					'user_agent',
					'remote_ip',
					'credit',
				],
                'choices' => array(
                    'date' => __( 'Date', 'acf-frontend-form-element' ),
					'time' => __( 'Time', 'acf-frontend-form-element' ),
					'page_url' => __( 'Page URL', 'elementor-pro' ),
					'user_agent' => __( 'User Agent', 'acf-frontend-form-element' ),
					'remote_ip' => __( 'Remote IP', 'acf-frontend-form-element' ),
					'credit' => __( 'Credit', 'acf-frontend-form-element' ),
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'ui' => 1,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
    ),
);